name: Setup Clarinet
description: Install Clarinet CLI for Clarity contract development

inputs:
  version:
    description: 'Clarinet version'
    required: false
    default: '3.14.0'

runs:
  using: composite
  steps:
    - name: Install Clarinet
      shell: bash
      run: |
        CLARINET_VERSION="${{ inputs.version }}"

        # Detect OS
        case "$(uname -s)" in
            Linux*)
                OS="linux"
                ;;
            Darwin*)
                OS="darwin"
                ;;
            *)
                echo "Unsupported OS"
                exit 1
                ;;
        esac

        # Detect architecture
        case "$(uname -m)" in
            x86_64|amd64)
                ARCH="x64"
                ;;
            aarch64|arm64)
                ARCH="arm64"
                ;;
            *)
                echo "Unsupported architecture"
                exit 1
                ;;
        esac

        # Download and install Clarinet
        curl --proto '=https' --tlsv1.2 -sSfL "https://github.com/hirosystems/clarinet/releases/download/v${CLARINET_VERSION}/clarinet-${CLARINET_VERSION}-${OS}-${ARCH}.tar.gz" | tar -xz

        # Move to local bin
        mv clarinet /usr/local/bin/

        # Verify installation
        clarinet --version

    - name: Cache Clarinet
      uses: actions/cache@v4
      with:
        path: ~/.clarinet
        key: clarinet-${{ runner.os }}-${{ inputs.version }}
